# Generated by Django 5.2.2 on 2025-06-11 13:08

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=shop.models.user_directory_path),
        ),
    ]
