# Generated by Django 5.2.2 on 2025-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Chattogram', 'Chattogram'), ('Mymenshing', 'Mymenshing'), ('Sylhet', 'Sylhet')], max_length=50, null=True),
        ),
    ]
