# Generated by Django 5.2.2 on 2025-06-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
