# Generated by Django 5.2.6 on 2025-09-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-shirt'), ('pant', 'Pant'), ('jacket', 'Jacket'), ('hoodie', 'Hoodie'), ('watches', 'Watches'), ('bags', 'Bags'), ('belts', 'Belts'), ('sunglasses', 'Sunglasses'), ('sandals', 'Sandals'), ('boots', 'Boots'), ('loafers', 'Loafers'), ('sneakers', 'Sneakers')], max_length=10),
        ),
    ]
